version: "2"
services:
  dev:
    build: .
    restart: always
    command: npm run serve
    volumes:
      - ./studium/hosting:/src/studium
    working_dir: "/src/studium"
    ports:
      - "8080:8080"

